# -*- coding: utf-8 -*-
"""B-tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGc0lR8zed2ZUFbTluKEzXsNeJBfRP0D
"""

class Book:
    def __init__(self, isbn, title, author):
        self.isbn = isbn
        self.title = title
        self.author = author

    def __repr__(self):
        return f"[{self.isbn}] {self.title} - {self.author}"


class BookBTreeNode:
    def __init__(self, t, leaf=False):
        self.t = t
        self.leaf = leaf
        self.keys = []   # ISBN brojevi
        self.values = [] # Book objekti
        self.children = []

    def traverse(self):
        for i in range(len(self.keys)):
            if not self.leaf:
                self.children[i].traverse()
            print(self.values[i])
        if not self.leaf:
            self.children[-1].traverse()

    def search(self, k):
        i = 0
        while i < len(self.keys) and k > self.keys[i]:
            i += 1

        if i < len(self.keys) and self.keys[i] == k:
            return self.values[i]

        if self.leaf:
            return None

        return self.children[i].search(k)

    def insert_non_full(self, k, v):
        i = len(self.keys) - 1

        if self.leaf:
            while i >= 0 and k < self.keys[i]:
                i -= 1
            self.keys.insert(i + 1, k)
            self.values.insert(i + 1, v)
        else:
            while i >= 0 and k < self.keys[i]:
                i -= 1
            i += 1
            if len(self.children[i].keys) == 2 * self.t - 1:
                self.split_child(i)
                if k > self.keys[i]:
                    i += 1
            self.children[i].insert_non_full(k, v)

    def split_child(self, i):
      t = self.t
      y = self.children[i]
      z = BookBTreeNode(t, y.leaf)

      # Pravo razdvajanje ključeva i vrednosti
      z.keys = y.keys[t:]        # desna polovina
      z.values = y.values[t:]

      # Srednji ključ ide u roditelja
      self.keys.insert(i, y.keys[t - 1])
      self.values.insert(i, y.values[t - 1])

      # Leva polovina ostaje u y
      y.keys = y.keys[:t - 1]
      y.values = y.values[:t - 1]

      if not y.leaf:
          z.children = y.children[t:]
          y.children = y.children[:t]

      self.children.insert(i + 1, z)

    def remove(self, k):
        idx = 0
        while idx < len(self.keys) and self.keys[idx] < k:
            idx += 1

        if idx < len(self.keys) and self.keys[idx] == k:
            if self.leaf:
                self.keys.pop(idx)
                self.values.pop(idx)
            else:
                if len(self.children[idx].keys) >= self.t:
                    pred_key, pred_val = self.get_predecessor(idx)
                    self.keys[idx] = pred_key
                    self.values[idx] = pred_val
                    self.children[idx].remove(pred_key)
                elif len(self.children[idx + 1].keys) >= self.t:
                    succ_key, succ_val = self.get_successor(idx)
                    self.keys[idx] = succ_key
                    self.values[idx] = succ_val
                    self.children[idx + 1].remove(succ_key)
                else:
                    self.merge(idx)
                    self.children[idx].remove(k)
        else:
            if self.leaf:
                return
            flag = (idx == len(self.keys))
            if len(self.children[idx].keys) < self.t:
                self.fill(idx)
            if flag and idx > len(self.keys):
                self.children[idx - 1].remove(k)
            else:
                self.children[idx].remove(k)

    def get_predecessor(self, idx):
        current = self.children[idx]
        while not current.leaf:
            current = current.children[-1]
        return current.keys[-1], current.values[-1]

    def get_successor(self, idx):
        current = self.children[idx + 1]
        while not current.leaf:
            current = current.children[0]
        return current.keys[0], current.values[0]

    def merge(self, idx):
        child = self.children[idx]
        sibling = self.children[idx + 1]
        child.keys.append(self.keys[idx])
        child.values.append(self.values[idx])
        child.keys.extend(sibling.keys)
        child.values.extend(sibling.values)
        if not child.leaf:
            child.children.extend(sibling.children)
        self.keys.pop(idx)
        self.values.pop(idx)
        self.children.pop(idx + 1)

    def fill(self, idx):
        if idx != 0 and len(self.children[idx - 1].keys) >= self.t:
            self.borrow_from_prev(idx)
        elif idx != len(self.children) - 1 and len(self.children[idx + 1].keys) >= self.t:
            self.borrow_from_next(idx)
        else:
            if idx != len(self.children) - 1:
                self.merge(idx)
            else:
                self.merge(idx - 1)

    def borrow_from_prev(self, idx):
        child = self.children[idx]
        sibling = self.children[idx - 1]
        child.keys.insert(0, self.keys[idx - 1])
        child.values.insert(0, self.values[idx - 1])
        if not child.leaf:
            child.children.insert(0, sibling.children.pop())
        self.keys[idx - 1] = sibling.keys.pop()
        self.values[idx - 1] = sibling.values.pop()

    def borrow_from_next(self, idx):
        child = self.children[idx]
        sibling = self.children[idx + 1]
        child.keys.append(self.keys[idx])
        child.values.append(self.values[idx])
        if not child.leaf:
            child.children.append(sibling.children.pop(0))
        self.keys[idx] = sibling.keys.pop(0)
        self.values[idx] = sibling.values.pop(0)


class BookBTree:
    def __init__(self, t):
        self.root = None
        self.t = t

    def traverse(self):
        if self.root:
            self.root.traverse()

    def search(self, isbn):
        return self.root.search(isbn) if self.root else None

    def insert(self, book):
        k = book.isbn
        v = book
        if self.root is None:
            self.root = BookBTreeNode(self.t, True)
            self.root.keys.append(k)
            self.root.values.append(v)
        else:
            if len(self.root.keys) == 2 * self.t - 1:
                s = BookBTreeNode(self.t, False)
                s.children.append(self.root)
                s.split_child(0)
                idx = 0
                if k > s.keys[0]:
                    idx += 1
                s.children[idx].insert_non_full(k, v)
                self.root = s
            else:
                self.root.insert_non_full(k, v)

    def delete(self, isbn):
        if not self.root:
            return
        self.root.remove(isbn)
        if len(self.root.keys) == 0:
            if self.root.leaf:
                self.root = None
            else:
                self.root = self.root.children[0]

if __name__ == "__main__":
    tree = BookBTree(2)

    tree.insert(Book(978014, "1984", "George Orwell"))
    tree.insert(Book(978030, "The Hobbit", "J.R.R. Tolkien"))
    tree.insert(Book(978045, "Fahrenheit 451", "Ray Bradbury"))
    tree.insert(Book(978067, "Dune", "Frank Herbert"))

    print("Sve knjige u biblioteci:")
    tree.traverse()

    print("\nPretraga ISBN 978045:")
    book = tree.search(978045)
    if book:
        print("Pronađena knjiga:", book)
    else:
        print("Knjiga nije pronađena.")

    print("\nBrišem knjigu sa ISBN 978030 (The Hobbit)...")
    tree.delete(978030)

    print("Knjige nakon brisanja:")
    tree.traverse()